[build]
  publish = "out"
  command = "npm run build:netlify"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
  BUILD_EXPORT = "true"

# Headers de performance e segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "origin-when-cross-origin"
    X-DNS-Prefetch-Control = "on"

# Cache otimizado para assets estáticos
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirects específicos
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

# Configurações de contexto
[context.production.environment]
  NODE_ENV = "production"
  NETLIFY_URL = "https://mittosdocabula.netlify.app"

[context.deploy-preview.environment]
  NODE_ENV = "production"

[context.branch-deploy.environment]
  NODE_ENV = "production"

# Configurações de função (para futuras APIs)
[functions]
  node_bundler = "esbuild"

# Configurações de performance
[template.environment]
  HUGO_VERSION = "0.54.0"